name: touch_bar_macos
description: macOS implementation of the touch_bar plugin.
version: 0.2.0-alpha.1
homepage: https://github.com/vital-edu/touch_bar_flutter_plugin/tree/master/touch_bar_macos
repository: https://github.com/vital-edu/touch_bar_flutter_plugin/

flutter:
  plugin:
    implements: touch_bar
    platforms:
      macos:
        pluginClass: TouchBarPlugin
        fileName: touch_bar_macos.dart

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  touch_bar_platform_interface: ^0.2.0-alpha.1

dev_dependencies:
  pedantic: ^1.11.0
